### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by supervital** [kaushikgopal/RxJava-Android-Samples#15] opened 2015-07-05 13:41 UTC
Hi Kaushik, thanks for yours examples about RxJava. I`ve just started learning it. I investigated RxJava with Retrofit, and found an issue. When the request being done to server, an exception is thrown with 403 error. onError called, an exception logged. looks Ok.
The issue is - when I close the app with back button, and open again, and do the request again, exception is thrown, and 2 errors was logged. Do the same steps, onError was called, 3 erros was logged, etc. Memory leak occurs.

Firstly - it seems strange, the Observable finished with an error, onError was called, app was closed with back button, onDestroy was called, all objects should be garbage collected.Isn't it ?

Ok, I tried to call unsubscribe on OnDestroy, the issue still reproduce.
I googled the issue and found workaround using WeakReference. It looks awkwardly.

What is your opinion about this ? Or, I did something wrong ?

**Comment by kaushikgopal** [comment] 2015-07-05 18:09
Hiya.

Sure let's try to break it down and get to the bottom of the issue.

The first problem you described seems like your not unsubscribing from the
observable at the end of the life cycle. Help me answer these questions:

1. Did you pull the latest code from the repo? (I recently pushed some
fixes)
2. Which example specifically are you trying ? Give me the name of the
class from the sample repo.

**Comment by supervital** [comment] 2015-07-06 08:54
1. No, I didn`t.
2. I was trying the RetrofitFragment. 

The interesting thing is that I unsubscribe on OnDestroy of that fragment. In the example the Observable was not unsubscribed, so, I created the local Subscriber, init it by button click, and unsubscribe on OnDestroy.

I have just pulled the changes and the issue still reproducing. I was debugging and the Observable is being unsubscribed.

Steps to reproduce:

1. Turn off the internet (to simulate no internet connection exception)
2. Open the Retrofit-RxJava example.
3. Press the button.
4. onError observer is called. Error logged.
5. close the app with back button.
6. do 2,3 steps
7. two onError is called. 2 Error logged.

Kill the process - helps to fix the issue.
Looks like Observable holds the Activities reference, even app was closed with back button.

**Comment by kaushikgopal** [comment] 2015-07-06 22:37
excellent catch! couple of points:

a. the "leak" was not being caused by any of the Rx activity. so the Retrofit + RxJava combination was not causing any of the issues. I tested this by removing all Rx related stuff from the fragment and put a debug log statement in the `onResume` method. You'll notice multiple instances of the fragment being created.
b. while i cannot pinpoint and tell you exactly what went wrong, i cleaned up the fragment construction and the backstack. This solved the problem. If you have a look at #a0b2e2d you'll see the differences. Essentially i remove the usless activity_main layout, and when adding fragments i used `android.R.id.content` instead of the custom id. 

i didn't have the patience to exactly find out at which point the issue was being caused, but needless to say post cleanup the multiple fragment instances don't show up.

i'm going ahead and closing this issue. thanks for letting me know. if you're still facing issues, let me know and i'll reopen.

**Closed by kaushikgopal** 2015-07-06 22:37 UTC

**Comment by supervital** [comment] 2015-07-07 07:37
Yes, the issue is resolved.

Thanks for your contribution to RxJava tutorials! The examples are clear and useful! :)
